name: alpha package push

# https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-alpha[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack --configuration Release --include-symbols /p:Version=${VERSION} --output . ./src/
    - name: Push
      run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY} --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}